#!/bin/bash

function install_tools(){
	echo "[+] PortSwigger https://portswigger.net/burp/communitydownload"
	cd /opt
	git clone https://github.com/danielmiessler/SecLists
	git clone https://github.com/carlospolop/PEASS-ng
	git clone https://gitlab.com/kalilinux/packages/windows-binaries
	git clone https://github.com/samratashok/nishang.git
	git clone https://github.com/sqlmapproject/sqlmap.git

	# Juicy Potato
	mkdir Juicy-Potato
	cd Juicy-Potato
	wget https://github.com/ohpe/juicy-potato/releases/download/v0.1/JuicyPotato.exe
	cd ..

	# Monkey PHP
	mkdir monkey-php-shell
	cd monkey-php-shell
	wget https://raw.githubusercontent.com/pentestmonkey/php-reverse-shell/master/php-reverse-shell.php
	cd ..

	# Impacket
	git clone https://github.com/SecureAuthCorp/impacket
	cd impacket
	python3 -m pip install .
	cd ..
	
	# smbmap
	git clone https://github.com/ShawnDEvans/smbmap.git
	cd smbmap
	python3 -m pip install -r requirements.txt
	cd ..

}

function delete_packages(){
	packages_to_delete="gnome-boxes gnome-books gnome-calculator gnome-calendar gnome-maps gnome-music gnome-contacts gnome-weather cheese"
	pacman -R $packages_to_delete --noconfirm &>/dev/null
}

function install_packages(){
	packages_to_install="xclip base-devel net-tools linux-headers open-vm-tools gtkmm3 gnome-tweaks opendoas tmux neofetch python-pip"
	pacman -S $packages_to_install --noconfirm &>/dev/null
}


function dash_to_dock() {
	echo "[+] Installing Dash to Dock"
	wget https://extensions.gnome.org/extension-data/dash-to-dockmicxgx.gmail.com.v71.shell-extension.zip &>/dev/null
	mkdir -p /home/$1/.local/share/gnome-shell/extensions
	unzip dash-to-dockmicxgx.gmail.com.v71.shell-extension.zip -d /home/$1/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com &>/dev/null
}

function theme(){
	mkdir /home/$1/github
	cd /home/$1/github

	echo "[+] Installing Orchis theme"
	git clone https://github.com/vinceliuice/Orchis-theme &>/dev/null
	cd Orchis-theme
	pacman -S gtk-engine-murrine gnome-themes-extra gnome-themes-standard sassc --noconfirm &>/dev/null
	./install --tweaks solid
	cd /home/$1/github

	echo "[+] Installing Kora icons"
	git clone https://github.com/bikass/kora.git &>/dev/null
	cd ./kora
	mkdir -p /home/$1/.local/share/icons
	cp -r ./kora* /home/$1/.local/share/icons
}

function conf_doas(){
	echo "[+] Editing doas.conf"
	echo "permit :wheel" > /etc/doas.conf
	echo "permit :root" >> /etc/doas.conf
	chown -c root:root /etc/doas.conf &>/dev/null
	chmod -c 0400 /etc/doas.conf &>/dev/null
}


function yay_install(){
	echo "[+] Installing yay"
	cd /opt
	git clone https://aur.archlinux.org/yay.git &>/dev/null
	chown -R $1:users ./yay
	cd ./yay
	doas -u $1 makepkg -si &>/dev/null
}

if [ "$(echo $UID)" != "0" ]; then
	echo "You must run this script as root user"
else
	echo "[+] Updating packages..."
	pacman -Syu --noconfirm &>/dev/null
	echo "Enter your username: "
	read user
	conf_doas
	yay_install $user
	theme $user
	dash_to_dock $user
	vmware
	delete_packages
	install_packages
fi
